server:
  port: 8010

spring:
  application:
    name: server-book
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
feign:
  httpclient:
    connection-timeout: 5000