server:
  port: 8020

spring:
  application:
    name: provide2
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always

logging:
  level:
    root: info
    com.mt: info
  file:
    max-size: 20MB
    path: application-log

user:
  defaultPwd: 123456