version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
    command: [
      "--character-set-server=utf8",
      "--log-bin=mysql-bin",
      "--server-id=1"
    ]
volumes:
  data: