eureka:
  client:
    service-url:
      defaultZone: http://server-eureka:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true