server:
  port: 8080

spring:
  application:
    name: mt-cloud-gateway
  profiles:
    active: local
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: book
        uri: lb://mt-cloud-book
        predicates:
        - Path=/book/**
        filters:
        - StripPrefix=1
      - id: base
        uri: lb://mt-cloud-base
        predicates:
        - Path=/base/**
        filters:
        - StripPrefix=1