version: '1.0'

services:
  eureka:
    build:
      context: ./mt-cloud-eureka/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-eureka:1.0
    restart: always
    container_name: mt-cloud-eureka
    hostname: mt-cloud-eureka
    ports:
      - "8000:8000"
    networks:
      iotnet:
        aliases:
          - mt-cloud-eureka

  gateway:
    build:
      context: ./mt-cloud-gateway/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-gateway:1.0
    restart: always
    container_name: mt-cloud-gateway
    hostname: mt-cloud-gateway
    ports:
      - "8080:8080"
    networks:
      iotnet:
        aliases:
          - mt-cloud-gateway

  base:
    build:
      context: ./mt-cloud-base/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-base:1.0
    restart: always
    container_name: mt-cloud-base
    hostname: mt-cloud-base
    ports:
      - "8010:8010"
    networks:
      iotnet:
        aliases:
          - mt-cloud-base

  book:
    build:
      context: ./mt-cloud-book/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-book:1.0
    restart: always
    container_name: mt-cloud-book
    hostname: mt-cloud-book
    ports:
      - "8020:8020"
    networks:
      iotnet:
        aliases:
          - mt-cloud-book


networks:
  iotnet:
    driver: 'bridge'