version: '2.2'

services:
  eureka:
    build:
      context: ./mt-cloud-dependency/mt-cloud-eureka/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-eureka:1.0
    restart: always
    container_name: mt-cloud-eureka
    hostname: mt-cloud-eureka
    environment:
      - "server.port=8000"
    ports:
      - "8000:8000"
    networks:
      iotnet:
        aliases:
          - mt-cloud-eureka

  gateway:
    build:
      context: ./mt-cloud-dependency/mt-cloud-gateway/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-gateway:1.0
    restart: always
    container_name: mt-cloud-gateway
    hostname: mt-cloud-gateway
    environment:
      - "server.port=8080"
      - "eureka.client.serviceUrl.defaultZone=http://mt-cloud-eureka:8000/eureka/"
      - "spring.cloud.config.discovery.enabled=true"
      - "spring.cloud.config.enabled=true"
      - "spring.cloud.config.profile=dev"
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    networks:
      iotnet:
        aliases:
          - mt-cloud-gateway

  config:
    build:
      context: ./mt-cloud-dependency/mt-cloud-config/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-config:1.0
    restart: always
    container_name: mt-cloud-config
    hostname: mt-cloud-config
    environment:
      - "server.port=8001"
      - "eureka.client.serviceUrl.defaultZone=http://mt-cloud-eureka:8000/eureka/"
    ports:
      - "8001:8001"
    depends_on:
      - eureka
    networks:
      iotnet:
        aliases:
          - mt-cloud-config

  auth:
    build:
      context: ./mt-cloud-center/mt-cloud-auth/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-auth:1.0
    restart: always
    container_name: mt-cloud-auth
    hostname: mt-cloud-auth
    environment:
      - "server.port=8010"
      - "eureka.client.serviceUrl.defaultZone=http://mt-cloud-eureka:8000/eureka/"
      - "spring.cloud.config.discovery.enabled=true"
      - "spring.cloud.config.enabled=true"
      - "spring.cloud.config.profile=dev"
    ports:
      - "8010:8010"
    depends_on:
      - eureka
      - config
    networks:
      iotnet:
        aliases:
          - mt-cloud-auth

  middle:
    build:
      context: ./mt-cloud-center/mt-cloud-middle/
      dockerfile: ./Dockerfile
    image:  mt-cloud/mt-cloud-middle:1.0
    restart: always
    container_name: mt-cloud-middle
    hostname: mt-cloud-middle
    environment:
      - "server.port=8020"
      - "eureka.client.serviceUrl.defaultZone=http://mt-cloud-eureka:8000/eureka/"
      - "spring.cloud.config.discovery.enabled=true"
      - "spring.cloud.config.enabled=true"
      - "spring.cloud.config.profile=dev"
    ports:
      - "8020:8020"
    depends_on:
      - eureka
      - config
    networks:
      iotnet:
        aliases:
          - mt-cloud-middle


networks:
  iotnet:
    driver: 'bridge'