server:
  port: 8001

spring:
  application:
    name: mt-cloud-config
  profiles:
    active: git # 使用的 Spring Cloud Config Server 的存储器方案
  cloud:
    config:
      server:
        # Spring Cloud Config Server 的 Git 存储器的配置项，对应 MultipleJGitEnvironmentProperties 类
        git:
          uri: https://github.com/motongb/mt-project-config.git # Git 仓库地址
          search-paths: /mt-cloud # 读取文件的根地址
          default-label: master # 使用的默认分支，默认为 master
#          username: ${CODING_USERNAME} # 账号
#          password: ${CODING_PASSWORD} # 密码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true