version: "3"
services:
  seata-server:
    image: seataio/seata-server
    hostname: seata-server
    ports:
      - "18090:8091"
    volumes:
      - ./config:/root/seata-config
    environment:
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry