server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: local
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: server1
          uri: lb://provide1
          predicates:
            - Path=/server1/**
          filters:
            - StripPrefix=1
        - id: server2
          uri: lb://provide2
          predicates:
            - Path=/server2/**
          filters:
            - StripPrefix=1