eureka:
  client:
    service-url:
      defaultZone: http://192.168.120.128:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true