server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: gateway
  profiles:
    active: local
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: book
        uri: lb://server-book
        predicates:
        - Path=/book/**
        filters:
        - StripPrefix=1
      - id: base
        uri: lb://server-base
        predicates:
        - Path=/base/**
        filters:
        - StripPrefix=1