server:
  port: 8010

spring:
  application:
    name: provide1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true