server:
  port: 8010

spring:
  application:
    name: mt-cloud-base
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always