spring:
  zipkin:
    base-url: http://192.168.122.10:9411
  sleuth:
    web:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true