spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iot_book?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

# mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.mt.book.dao: debug
  file:
    max-size: 20MB
    path: application-log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true

#分布式事务配置
seata:
  tx-service-group: book_group #事务组
  service:
    vgroup-mapping:
      book_group: seata-server #服务名
    grouplist:
      seata-server: 192.168.120.128:18090
  enabled: false
